version: '2'
services: 
  hello1:
    image: hellodevsu:prueba
    command: sh -c "python /home/app.py"
  hello2:
    image: hellodevsu:prueba
    command: sh -c "python /home/app.py"
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"